# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WakilniCustomerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for WakilniCustomerApp
  pod 'Firebase/Messaging'

#  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

#  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

#  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

#  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps' # Remove this line if you don't want to support GoogleMaps on iOS
#  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
#  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  target 'WakilniCustomerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
